server:
  port: 8080

spring:
  application:
    name: rest-api
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

logging:
  level:
    com.learning: DEBUG
