server:
  port: 8080

spring:
  application:
    name: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
  cache:
    type: redis
    redis:
      time-to-live: 600s
